ADD_DEFINITIONS(-DBOOST_LOG_DYN_LINK)

FIND_PACKAGE(Boost 1.58 COMPONENTS log OPTIONAL)
FIND_PACKAGE(Boost 1.58 COMPONENTS system OPTIONAL)

set(OS_SPECIFIC pthread rt)

set(BPUTIL_INCLUDE_DIRS, ${BPUTIL_INCLUDE_DIR})
set(BPUTIL_EXT_LIBRARIES  ${OS_SPECIFIC} ${Boost_SYSTEM_LIBRARY} ${Boost_LOG_LIBRARY})